### ISSUE TITLE
Why not reuse gtfs-csv2rdf from nodejs?

### ISSUE THREAD

**Issue by pietercolpaert** [diarmuidr3d/gtfs_csv_to_rdf.py#1]
Hey @diarmuidr3d,

Great to see that you're building this! Love to see that more transport data is getting into the linked data domain :)

I'm curious however why you're not just reusing https://github.com/opentransport/gtfs-csv2rdf and I would be glad, if it doesn't match your requirements, to collaborate there on something that does. What do you think?

**Comment by diarmuidr3d** [comment]
Hi @pietercolpaert,

Essentially I just wanted a project to keep myself amused so I got started on this, no major goal in mind other than a functioning conversion. :)

**Comment by pietercolpaert** [comment]
Ok, nevermind then, carry on! Although I would love your contributions on https://github.com/opentransport/gtfs-csv2rdf ;)

**Comment by diarmuidr3d** [comment]
I'll keep an eye on it :)

Then main confusion I'm having at the moment is getting the Literal types right. As far as I can tell at the moment, all literals (that I've looked at, so Stops and Agency) are XSD.string?

**Comment by pietercolpaert** [comment]
A lot of them are xsd:string, others include:
- stoptimes.arrivalTime & departureTime: xsd:duration (duration from midnight on a certain day)
- service.startDate & endDate: xsd:date
- service.monday ... friday: xsd:boolean
- ...

**Comment by diarmuidr3d** [comment]
Ah excellent, yeah, I just wanted to make sure as I nearly missed the types for wheelchair accessibility!

Thank you.
